services:
  postgres:
    image: postgres:latest
    container_name: ai-workqueue
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitMQ:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

volumes:
  postgres_data:
